from __future__ import annotations

__version__: str

class Index:
    def __init__(self) -> None: ...
    def build(self, fname: str, iteration: int) -> None: ...
    def build_from_graphs(
        self,
        graphs: list[tuple[list[int], list[tuple[int, int, int]]]],
        iteration: int,
    ) -> None: ...
    def save(self, path: str) -> None: ...
    def load(self, path: str) -> None: ...
    def encode_query_file(self, fname: str) -> list[list[int]]: ...
    def encode_query_graphs(
        self, graphs: list[tuple[list[int], list[tuple[int, int, int]]]]
    ) -> list[list[int]]: ...
    def search_encoded(
        self, query: list[int], threshold: float
    ) -> list[tuple[int, float]]: ...
    @property
    def num_graphs(self) -> int: ...
    @property
    def matrix_depth(self) -> int: ...
    @property
    def iterations(self) -> int: ...
    @property
    def index_length(self) -> int: ...
    @property
    def memory_bytes(self) -> int: ...
